### ISSUE TITLE
issue running Addin

### ISSUE THREAD

**Issue by GeoffreyDenie** [MjMthimunye/RevitPluginSample#1]
Hi Jacobian, 
I downloaded your script for making a ribbon in Revit. 
Since I am using Revit 2024, I changed the information in the Debug Properties to Revit 2024. 

However when I run the debugger and Revit opens the debugger give's me the following error: 

System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\Users\32478\AppData\Roaming\Autodesk\Revit\Addins\2024\Resources\jacobian.ico'.'

Do you know what can be the cause of this? 

thanks

**Comment by MjMthimunye** [comment]
Revit cant find the icon image in the Resources folder. 
Make sure you copy the icon image in the post build.
